.nh
.TH "GO-FDO-CLIENT" "1" "go-fdo-client" "Go FDO Client"

.SH NAME
go-fdo-client - FIDO Device Onboard (FDO) client


.SH SYNOPSIS
\fBgo-fdo-client {device-init|onboard|print} [flags]\fP


.SH DESCRIPTION
Run an FDO client to initialize or onboard a device.

.PP
Use one of the subcommands to perform device initialization (DI) with a
manufacturer server, onboard a device via TO1/TO2, or print the stored
device credentials.


.SH OPTIONS
\fB--blob\fP=""
	File path of device credential blob

.PP
\fB--config\fP=""
	Path to configuration file (YAML or TOML)

.PP
\fB--debug\fP[=false]
	Print HTTP contents

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for go-fdo-client

.PP
\fB--key\fP=""
	Key type for device credential [options: ec256, ec384, rsa2048, rsa3072]

.PP
\fB--tpm\fP=""
	Use a TPM at path for device credential secrets


.SH EXAMPLE
.EX
  # Initialize a device with a manufacturer server:
  go-fdo-client device-init http://127.0.0.1:8038 --key ec256 --blob cred.bin

  # Onboard a previously initialized device:
  go-fdo-client onboard --key ec256 --kex ECDH256 --blob cred.bin
.EE


.SH SEE ALSO
\fBgo-fdo-client-device-init(1)\fP, \fBgo-fdo-client-onboard(1)\fP, \fBgo-fdo-client-print(1)\fP
