.nh
.TH "GO-FDO-CLIENT-ONBOARD" "1" "go-fdo-client" "Go FDO Client"

.SH NAME
go-fdo-client-onboard - Run FDO TO1 and TO2 onboarding


.SH SYNOPSIS
\fBgo-fdo-client onboard [flags]\fP


.SH DESCRIPTION
Run FDO TO1 and TO2 onboarding to transfer device ownership to the owner server.
The device must have been initialized (device-init) before running onboard.
At least one of --blob or --tpm is required to access device credentials.


.SH OPTIONS
\fB--allow-credential-reuse\fP[=false]
	Allow credential reuse protocol during onboarding

.PP
\fB--cipher\fP="A128GCM"
	Name of cipher suite to use for encryption (see usage)

.PP
\fB--default-working-dir\fP=""
	Default working directory for all FSIMs (fdo.command, fdo.download, fdo.upload, fdo.wget) (default: current working directory)

.PP
\fB--enable-interop-test\fP[=false]
	Enable FIDO Alliance interop test module (fsim.Interop)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for onboard

.PP
\fB--insecure-tls\fP[=false]
	Skip TLS certificate verification

.PP
\fB--kex\fP=""
	Name of cipher suite to use for key exchange (see usage)

.PP
\fB--max-serviceinfo-size\fP=1300
	Maximum service info size to receive

.PP
\fB--resale\fP[=false]
	Perform resale

.PP
\fB--to2-retry-delay\fP=0s
	Delay between failed TO2 attempts when trying multiple Owner URLs from same RV directive (0=disabled)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--blob\fP=""
	File path of device credential blob

.PP
\fB--config\fP=""
	Path to configuration file (YAML or TOML)

.PP
\fB--debug\fP[=false]
	Print HTTP contents

.PP
\fB--key\fP=""
	Key type for device credential [options: ec256, ec384, rsa2048, rsa3072]

.PP
\fB--tpm\fP=""
	Use a TPM at path for device credential secrets


.SH EXAMPLE
.EX

  # Using CLI arguments:
  go-fdo-client onboard --key ec256 --kex ECDH256 --blob cred.bin

  # Using config file:
  go-fdo-client onboard --config config.yaml

  # Mix CLI and config (CLI takes precedence):
  go-fdo-client onboard --config config.yaml --cipher A256GCM
.EE


.SH SEE ALSO
\fBgo-fdo-client(1)\fP
